Repository openedx/tutor-contrib-aspects, pull requests merged in 2023-07, with the labels that each got.

#125 feat: allow to import dashboards roles
  tutoraspects/templates/aspects/apps/superset/pythonpath/assets.yaml
  tutoraspects/templates/aspects/apps/superset/pythonpath/create_assets.py
  tutoraspects/templates/aspects/jobs/init/superset/init-superset.sh
Labels: open-source-contribution

#138 feat: allow to install extra dbt packages
  README.rst
  tutoraspects/plugin.py
  tutoraspects/templates/aspects/apps/aspects/dbt/dbt_project.yml
  tutoraspects/templates/aspects/apps/aspects/dbt/packages.yml
  tutoraspects/templates/aspects/apps/aspects/scripts/dbt.sh
Labels: open-source-contribution

#134 feat: use display names for entities instead of ID (FC-0024)
  tutoraspects/templates/aspects/apps/superset/pythonpath/assets.yaml
  tutoraspects/templates/aspects/apps/superset/pythonpath/queries/dim_course_videos.sql
  tutoraspects/templates/aspects/apps/superset/pythonpath/queries/dim_courses.sql
  tutoraspects/templates/aspects/apps/superset/pythonpath/queries/fact_enrollments.sql
  tutoraspects/templates/aspects/apps/superset/pythonpath/queries/fact_transcript_usage.sql
  tutoraspects/templates/aspects/apps/superset/pythonpath/queries/fact_video_plays.sql
Labels: waiting on author, open-source-contribution

#99 feat: add support for migrations
  tutoraspects/plugin.py
  tutoraspects/templates/aspects/apps/aspects/migrations/README.rst
  tutoraspects/templates/aspects/apps/aspects/migrations/alembic.ini
  tutoraspects/templates/aspects/apps/aspects/migrations/alembic/env.py
  tutoraspects/templates/aspects/apps/aspects/migrations/alembic/script.py.mako
  tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0001_get_org_from_course_url.py
  tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0002_raw_xapi_table.py
  tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0003_enrollment.py
  tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0004_video.py
  tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0005_problem.py
  tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0006_navigation.py
  tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0007_event_sink.py
  tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0008_vector.py
  tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/__init__.py
  tutoraspects/templates/aspects/apps/aspects/scripts/alembic.sh
  tutoraspects/templates/aspects/apps/aspects/scripts/clickhouse-demo-xapi-data.sh
  tutoraspects/templates/aspects/apps/aspects/scripts/dbt.sh
  tutoraspects/templates/aspects/apps/superset/pythonpath/assets.yaml
  tutoraspects/templates/aspects/build/aspects/Dockerfile
  tutoraspects/templates/aspects/build/aspects/requirements.txt
  tutoraspects/templates/aspects/jobs/init/aspects/init-aspects.sh
  tutoraspects/templates/aspects/jobs/init/clickhouse/init-clickhouse.sh
Labels: waiting on author, open-source-contribution, core contributor

#146 feat: add chart for active enrollments per day (FC-0024)
  README.rst
  tutoraspects/templates/aspects/apps/superset/pythonpath/assets.yaml
  tutoraspects/templates/aspects/apps/superset/pythonpath/queries/fact_enrollments.sql
  tutoraspects/templates/aspects/apps/superset/pythonpath/queries/fact_enrollments_by_day.sql
Labels: open-source-contribution

#139 feat: backward compatibility with tutor14
  .gitignore
  tutoraspects/commands_v0.py
  tutoraspects/commands_v1.py
  tutoraspects/plugin.py
  tutoraspects/templates/aspects/build/aspects-superset/Dockerfile
Labels: open-source-contribution

#150 refactor: move assets outside volumes
  README.rst
  tutoraspects/templates/aspects/apps/superset/pythonpath/assets.yaml
  tutoraspects/templates/aspects/build/aspects/Dockerfile
  tutoraspects/templates/openedx-assets/Cumulative_enrollments_by_mode_15.yaml
  tutoraspects/templates/openedx-assets/Enrolled_learners_per_day_36.yaml
  tutoraspects/templates/openedx-assets/Enrollment_events_per_day_16.yaml
  tutoraspects/templates/openedx-assets/Instructor_dashboard_9.yaml
  tutoraspects/templates/openedx-assets/Open_edX_Admin_Dashboard_2.yaml
  tutoraspects/templates/openedx-assets/OpenedX_Clickhouse.yaml
  tutoraspects/templates/openedx-assets/Transcript_closed_captioning_usage_per_video_11.yaml
  tutoraspects/templates/openedx-assets/Watches_per_video_10.yaml
  tutoraspects/templates/openedx-assets/course_blocks.yaml
  tutoraspects/templates/openedx-assets/course_overviews.yaml
  tutoraspects/templates/openedx-assets/dim_courses.yaml
  tutoraspects/templates/openedx-assets/fact_enrollments.yaml
  tutoraspects/templates/openedx-assets/fact_enrollments_by_day.yaml
  tutoraspects/templates/openedx-assets/fact_transcript_usage.yaml
  tutoraspects/templates/openedx-assets/fact_video_plays.yaml
  tutoraspects/templates/openedx-assets/queries/dim_course_videos.sql
  tutoraspects/templates/openedx-assets/queries/dim_courses.sql
  tutoraspects/templates/openedx-assets/queries/fact_enrollments.sql
  tutoraspects/templates/openedx-assets/queries/fact_enrollments_by_day.sql
  tutoraspects/templates/openedx-assets/queries/fact_transcript_usage.sql
  tutoraspects/templates/openedx-assets/queries/fact_video_plays.sql
  tutoraspects/templates/openedx-assets/xAPI_events_by_course_11.yaml
  tutoraspects/templates/openedx-assets/xAPI_problem_events_by_block_7.yaml
  tutoraspects/templates/openedx-assets/xapi_events_all_parsed.yaml
Labels: open-source-contribution

#147 test: add tests for tutor local env
  .ci/config.yml
  .github/workflows/test-tutor-aspects.yml
  tutoraspects/plugin.py
  tutoraspects/templates/aspects/build/aspects/Dockerfile
Labels: open-source-contribution

#156 test: correct tutor test workflow
  .github/workflows/test-tutor-aspects.yml
Labels: open-source-contribution

#158 feat: allow to run extra clickhouse sql
  README.rst
  tutoraspects/patches/clickhouse-extra-sql
  tutoraspects/templates/aspects/jobs/init/clickhouse/init-clickhouse.sh
Labels: open-source-contribution

#163 feat: add video timeline chart (FC-0024)
  tutoraspects/templates/aspects/apps/superset/pythonpath/assets.yaml
  tutoraspects/templates/openedx-assets/Instructor_dashboard_9.yaml
  tutoraspects/templates/openedx-assets/Watched_video_segments_51.yaml
  tutoraspects/templates/openedx-assets/dim_course_videos.yaml
  tutoraspects/templates/openedx-assets/fact_watched_video_segments.yaml
  tutoraspects/templates/openedx-assets/queries/dim_course_videos.sql
  tutoraspects/templates/openedx-assets/queries/fact_watched_video_segments.sql
Labels: open-source-contribution

#107 feat: add support for extra rlsf
  README.rst
  tutoraspects/patches/superset-row-level-security
  tutoraspects/templates/aspects/apps/superset/pythonpath/create_row_level_security.py
Labels: waiting on author, open-source-contribution, core contributor

#170 build: add ci workflow to build and push docker images
  .github/workflows/build-aspects.yaml
  .github/workflows/test-tutor-aspects.yml
Labels: open-source-contribution

#159 feat: add operator dashboard
  README.rst
  tutoraspects/patches/superset-row-level-security
  tutoraspects/plugin.py
  tutoraspects/templates/aspects/apps/superset/pythonpath/assets.yaml
  tutoraspects/templates/aspects/apps/superset/pythonpath/create_assets.py
  tutoraspects/templates/aspects/apps/superset/pythonpath/openedx_sso_security_manager.py
  tutoraspects/templates/aspects/apps/superset/pythonpath/superset_config_docker.py
  tutoraspects/templates/aspects/apps/superset/security/roles.json
  tutoraspects/templates/openedx-assets/Actor_IDs_over_time_47.yaml
  tutoraspects/templates/openedx-assets/Courses_44.yaml
  tutoraspects/templates/openedx-assets/Event_type_45.yaml
  tutoraspects/templates/openedx-assets/Events_per_course_46.yaml
  tutoraspects/templates/openedx-assets/Instructor_dashboard_9.yaml
  tutoraspects/templates/openedx-assets/Last_course_syncronized_41.yaml
  tutoraspects/templates/openedx-assets/Last_received_xAPI_events_40.yaml
  tutoraspects/templates/openedx-assets/Open_edX_Admin_Dashboard_2.yaml
  tutoraspects/templates/openedx-assets/Operator_Dashboard_5.yaml
  tutoraspects/templates/openedx-assets/Organizations_42.yaml
  tutoraspects/templates/openedx-assets/Synchronized_Courses_39.yaml
  tutoraspects/templates/openedx-assets/Unique_actors_43.yaml
  tutoraspects/templates/openedx-assets/xAPI_events_38.yaml
Labels: open-source-contribution

#173 build: build docker images on release created
  .github/workflows/build-aspects.yaml
Labels: open-source-contribution

#177 build: trigger build jobs after release
  .github/workflows/build-aspects.yaml
  .github/workflows/release.yaml
Labels: open-source-contribution

#182 feat: backfill course data command
  README.rst
  tutoraspects/commands_v0.py
  tutoraspects/commands_v1.py
  tutoraspects/plugin.py
  tutoraspects/templates/aspects/jobs/init/init-lms.sh
  tutoraspects/templates/aspects/jobs/init/init-mysql.sh
Labels: open-source-contribution

#185 build: push openedx-dev cache to registry
  .github/workflows/release.yaml
Labels: open-source-contribution

#187 build: change default title for release PR
  .github/workflows/bump-version.yaml
Labels: open-source-contribution

#183 feat: import superset extra roles
  README.rst
  tutoraspects/patches/superset-extra-roles
  tutoraspects/patches/superset-sso-assignment-rules
  tutoraspects/templates/aspects/apps/superset/pythonpath/openedx_sso_security_manager.py
  tutoraspects/templates/aspects/apps/superset/security/roles.json
Labels: open-source-contribution

#193 refactor: parse course key in MV queries (FC-0024)
  tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0009_prefer_course_key.py
  tutoraspects/templates/openedx-assets/queries/fact_enrollments.sql
  tutoraspects/templates/openedx-assets/queries/fact_learner_problem_summary.sql
  tutoraspects/templates/openedx-assets/queries/fact_problem_responses.sql
  tutoraspects/templates/openedx-assets/queries/fact_transcript_usage.sql
  tutoraspects/templates/openedx-assets/queries/fact_video_plays.sql
  tutoraspects/templates/openedx-assets/queries/fact_watched_video_segments.sql
Labels: open-source-contribution

#200 docs: Instructions to Sink Historical event data to ClickHouse
  README.rst
Labels: needs test run, open-source-contribution

#198 Update readme
  README.rst
  tutoraspects/patches/k8s-deployments
  tutoraspects/patches/k8s-jobs
  tutoraspects/patches/local-docker-compose-jobs-services
  tutoraspects/patches/local-docker-compose-services
  tutoraspects/templates/aspects/jobs/init/init-lms.sh
Labels: open-source-contribution

#199 fix: block only students
  tutoraspects/templates/aspects/apps/superset/pythonpath/openedx_sso_security_manager.py
  tutoraspects/templates/aspects/apps/superset/security/roles.json
Labels: waiting on author, open-source-contribution, core contributor

#203 Fg/fix o auth token refresh
  tutoraspects/templates/aspects/apps/superset/pythonpath/openedx_sso_security_manager.py
Labels: open-source-contribution
