Repository openedx/tutor-contrib-aspects, pull requests merged in 2023-06, with the labels that each got.

#51 fix: allow to import dashboards in k8s
  tutoroars/patches/k8s-jobs
  tutoroars/patches/kustomization-configmapgenerator
  tutoroars/plugin.py
  tutoroars/templates/oars/apps/data/superset/charts/Course_Enrollments_6.yaml
  tutoroars/templates/oars/apps/data/superset/charts/Problem_Difficulty_9.yaml
  tutoroars/templates/oars/apps/data/superset/charts/Video_events_7.yaml
  tutoroars/templates/oars/apps/data/superset/charts/xAPI_events_1.yaml
  tutoroars/templates/oars/apps/data/superset/charts/xAPI_events_by_course_3.yaml
  tutoroars/templates/oars/apps/data/superset/charts/xAPI_problem_events_by_block_2.yaml
  tutoroars/templates/oars/apps/data/superset/dashboards/Open_edX_Dashboard_1.yaml
  tutoroars/templates/oars/apps/data/superset/metadata.yaml
  tutoroars/templates/oars/apps/pythonpath/requirements.txt
  tutoroars/templates/oars/apps/pythonpath/superset-dashboard.py
  tutoroars/templates/oars/jobs/init/superset-api-dashboard.sh
Labels: open-source-contribution

#55 feat: add support for different actor_id sources
  tutoroars/templates/oars/jobs/init/oars_init_schemas_tables_users.sh
Labels: open-source-contribution

#62 feat: move superset into OARS plugin
  Makefile
  tutoroars/patches/caddyfile
  tutoroars/patches/k8s-deployments
  tutoroars/patches/k8s-jobs
  tutoroars/patches/k8s-services
  tutoroars/patches/kustomization-configmapgenerator
  tutoroars/patches/local-docker-compose-dev-services
  tutoroars/patches/local-docker-compose-jobs-services
  tutoroars/patches/local-docker-compose-services
  tutoroars/plugin.py
  tutoroars/templates/base-docker-compose-services
  tutoroars/templates/oars/apps/superset/.gitignore
  tutoroars/templates/oars/apps/superset/data/roles.json
  tutoroars/templates/oars/apps/superset/docker/docker-bootstrap.sh
  tutoroars/templates/oars/apps/superset/docker/requirements-local.txt
  tutoroars/templates/oars/apps/superset/pythonpath/openedx_jinja_filters.py
  tutoroars/templates/oars/apps/superset/pythonpath/openedx_sso_security_manager.py
  tutoroars/templates/oars/apps/superset/pythonpath/superset_config.py
  tutoroars/templates/oars/apps/superset/pythonpath/superset_config_docker.py
  tutoroars/templates/oars/jobs/init/superset/init-mysql.sh
  tutoroars/templates/oars/jobs/init/superset/init-openedx.sh
  tutoroars/templates/oars/jobs/init/superset/init-superset.sh
Labels: open-source-contribution

#57 Creates materialized view for enrollment events (FC-0024)
  tutoroars/plugin.py
  tutoroars/templates/oars/jobs/init/clickhouse/oars_init_schemas_tables_users.sh
Labels: waiting on author, open-source-contribution

#65 fix: add missing bcrypt dependency
  setup.py
Labels: open-source-contribution

#66 feat: create high-level MVs and backing tables (FC-0024)
  tutoroars/plugin.py
  tutoroars/templates/oars/jobs/init/clickhouse/oars_init_schemas_tables_users.sh
Labels: waiting on author, open-source-contribution

#69 feat: allow to import custom dashboards
  .gitignore
  README.rst
  scripts/serialize-assets.py
  tutoroars/patches/k8s-deployments
  tutoroars/patches/k8s-jobs
  tutoroars/patches/k8s-volumes
  tutoroars/patches/kustomization-configmapgenerator
  tutoroars/patches/superset-extra-assets
  tutoroars/plugin.py
  tutoroars/templates/base-docker-compose-services
  tutoroars/templates/oars/apps/data/superset/charts/Course_Enrollments_6.yaml
  tutoroars/templates/oars/apps/data/superset/charts/Problem_Difficulty_9.yaml
  tutoroars/templates/oars/apps/data/superset/charts/Video_events_7.yaml
  tutoroars/templates/oars/apps/data/superset/charts/xAPI_events_1.yaml
  tutoroars/templates/oars/apps/data/superset/charts/xAPI_events_by_course_3.yaml
  tutoroars/templates/oars/apps/data/superset/charts/xAPI_problem_events_by_block_2.yaml
  tutoroars/templates/oars/apps/data/superset/dashboards/Open_edX_Dashboard_1.yaml
  tutoroars/templates/oars/apps/data/superset/databases/OpenedX_Clickhouse.yaml
  tutoroars/templates/oars/apps/data/superset/databases/OpenedX_MySQL.yaml
  tutoroars/templates/oars/apps/data/superset/datasets/OpenedX_Clickhouse/xapi_events_all_parsed.yaml
  tutoroars/templates/oars/apps/data/superset/datasets/OpenedX_MySQL/Course_Enrollments_Overview.yaml
  tutoroars/templates/oars/apps/data/superset/metadata.yaml
  tutoroars/templates/oars/apps/superset/pythonpath/assets.yaml
  tutoroars/templates/oars/apps/superset/pythonpath/create_assets.py
  tutoroars/templates/oars/apps/superset/security/roles.json
  tutoroars/templates/oars/jobs/init/superset/init-superset.sh
  tutoroars/templates/oars/jobs/init/superset/superset-api-dashboard.sh
Labels: open-source-contribution

#82 feat!: prefer verb_id for primary key in event MVs (FC-0024)
  tutoroars/templates/oars/jobs/init/clickhouse/oars_init_schemas_tables_users.sh
Labels: open-source-contribution

#80 feat: add support for ralph extra settings
  tutoroars/patches/k8s-deployments
  tutoroars/patches/k8s-jobs
  tutoroars/plugin.py
  tutoroars/templates/oars/apps/ralph/config/env
Labels: open-source-contribution

#87 fix: local superset-sso working
  tutoraspects/patches/k8s-deployments
  tutoraspects/patches/local-docker-compose-dev-services
  tutoraspects/patches/local-docker-compose-jobs-services
  tutoraspects/patches/local-docker-compose-services
  tutoraspects/plugin.py
  tutoraspects/templates/aspects/jobs/init/superset/init-openedx.sh
  tutoraspects/templates/base-docker-compose-services
Labels: open-source-contribution

#84 fix: smart parsing of starting_position (FC-0024)
  tutoraspects/templates/aspects/jobs/init/clickhouse/aspects_init_schemas_tables_users.sh
Labels: open-source-contribution

#89 fix: remove unused variables, do clean up work
  tutoraspects/patches/k8s-deployments
  tutoraspects/patches/k8s-jobs
  tutoraspects/plugin.py
  tutoraspects/templates/aspects/apps/superset/docker/requirements-local.txt
  tutoraspects/templates/aspects/apps/superset/pythonpath/assets.yaml
  tutoraspects/templates/aspects/jobs/init/superset/superset-init-security.sh
  tutoraspects/templates/base-docker-compose-services
Labels: open-source-contribution

#92 feat: use custom docker images for services
  .github/workflows/release.yaml
  CHANGELOG.md
  setup.cfg
  tutoraspects/patches/local-docker-compose-services
  tutoraspects/plugin.py
  tutoraspects/templates/aspects/apps/scripts/aspects/clickhouse-demo-xapi-data.sh
  tutoraspects/templates/aspects/apps/scripts/aspects/dbt.sh
  tutoraspects/templates/aspects/apps/scripts/aspects/requirements.txt
  tutoraspects/templates/aspects/apps/superset/docker/requirements-local.txt
  tutoraspects/templates/aspects/apps/superset/pythonpath/create_row_level_security.py
  tutoraspects/templates/aspects/build/aspects-superset/Dockerfile
  tutoraspects/templates/aspects/build/aspects-superset/requirements.txt
  tutoraspects/templates/aspects/build/aspects/Dockerfile
  tutoraspects/templates/aspects/jobs/init/clickhouse/aspects_init_schemas_tables_users.sh
  tutoraspects/templates/aspects/jobs/init/clickhouse/init-clickhouse.sh
  tutoraspects/templates/aspects/jobs/init/dbt/init-dbt.sh
  tutoraspects/templates/aspects/jobs/init/lms/configure-aspects-lms.sh
  tutoraspects/templates/aspects/jobs/init/superset/init-openedx.sh
  tutoraspects/templates/aspects/jobs/init/superset/init-superset.sh
  tutoraspects/templates/aspects/jobs/init/superset/superset-api-dashboard.sh
Labels: waiting on author, open-source-contribution, core contributor

#98 build: correct current version for release
  setup.cfg
Labels: open-source-contribution

#96 feat: create instructor dashboard with video data (FC-0024)
  tutoraspects/templates/aspects/apps/superset/pythonpath/assets.yaml
Labels: open-source-contribution

#94 refactor: simplify clickhouse port
  README.rst
  tutoraspects/patches/k8s-deployments
  tutoraspects/patches/k8s-jobs
  tutoraspects/patches/local-docker-compose-services
  tutoraspects/patches/openedx-cms-common-settings
  tutoraspects/plugin.py
  tutoraspects/templates/aspects/apps/ralph/config/env
  tutoraspects/templates/aspects/apps/scripts/aspects/clickhouse-demo-xapi-data.sh
  tutoraspects/templates/aspects/apps/scripts/aspects/profiles.yml
  tutoraspects/templates/aspects/apps/superset/pythonpath/assets.yaml
  tutoraspects/templates/aspects/apps/vector/partials/common-post.toml
  tutoraspects/templates/aspects/jobs/init/clickhouse/init-clickhouse.sh
Labels: open-source-contribution

#105 refactor: align aspects folder structure
  tutoraspects/patches/k8s-jobs
  tutoraspects/patches/kustomization-configmapgenerator
  tutoraspects/patches/local-docker-compose-jobs-services
  tutoraspects/plugin.py
  tutoraspects/templates/aspects/apps/aspects/dbt/profiles.yml
  tutoraspects/templates/aspects/apps/aspects/dbt/requirements.txt
  tutoraspects/templates/aspects/apps/aspects/scripts/clickhouse-demo-xapi-data.sh
  tutoraspects/templates/aspects/apps/aspects/scripts/dbt.sh
  tutoraspects/templates/aspects/jobs/init/dbt/init-dbt.sh
Labels: open-source-contribution

#106 build: fix release workflow
  .github/workflows/release.yaml
Labels: open-source-contribution

#111 build: back the release workflow
  .github/workflows/release.yaml
Labels: open-source-contribution

#118 build: release on push to bot branch
  .github/workflows/bump-version.yaml
  .github/workflows/pypi-publish.yml
  .github/workflows/release.yaml
Labels: open-source-contribution

#119 build: fix condition for release workflow
  .github/workflows/release.yaml
Labels: open-source-contribution

#110 refactor: create a separate database for dbt (FC-0024)
  README.rst
  tutoraspects/plugin.py
  tutoraspects/templates/aspects/apps/aspects/dbt/profiles.yml
  tutoraspects/templates/aspects/apps/superset/pythonpath/assets.yaml
  tutoraspects/templates/aspects/jobs/init/clickhouse/init-clickhouse.sh
Labels: open-source-contribution

#122 build: fix use correct branch destination
  .github/workflows/release.yaml
Labels: open-source-contribution

#123 feat: add support for extra jinja filters
  tutoraspects/patches/superset-jinja-filters
  tutoraspects/plugin.py
  tutoraspects/templates/aspects/apps/superset/pythonpath/openedx_jinja_filters.py
  tutoraspects/templates/aspects/apps/superset/pythonpath/superset_config_docker.py
Labels: open-source-contribution
