Repository openedx/tutor-contrib-aspects, pull requests merged in 2023-04, with the labels that each got.

#21 docs: improve project readme format
  README.rst
Labels: open-source-contribution

#20 fix: use SUPERSET_HOST instead of superset
  tutoroars/templates/oars/apps/pythonpath/superset-dashboard.py
Labels: open-source-contribution

#22 build: add useful workflows for maintenance
  .github/workflows/pypi-publish.yml
  .github/workflows/test.yml
  .github/workflows/upgrade-python-requirements.yml
  Makefile
  README.rst
  requirements/base.in
  requirements/base.txt
  requirements/common_constraints.txt
  requirements/constraints.txt
  requirements/dev.in
  requirements/dev.txt
  requirements/pip-tools.in
  requirements/pip-tools.txt
  requirements/pip.in
  requirements/pip.txt
  setup.py
  tutoroars/__about__.py
  tutoroars/plugin.py
  tutoroars/templates/oars/apps/pythonpath/superset-dashboard.py
Labels: waiting on author, open-source-contribution, core contributor

#24 feat: add k8s related files
  tutoroars/patches/k8s-jobs
  tutoroars/patches/kustomization-configmapgenerator
  tutoroars/plugin.py
  tutoroars/templates/oars/apps/data/clickhouse/coursegraph_nodes.csv
  tutoroars/templates/oars/apps/data/clickhouse/coursegraph_relationships.csv
  tutoroars/templates/oars/apps/data/superset/databases/OpenedX_Clickhouse.yaml
  tutoroars/templates/oars/apps/data/superset/databases/OpenedX_MySQL.yaml
  tutoroars/templates/oars/jobs/init/oars_init_schemas_tables_users.sh
  tutoroars/templates/oars/jobs/init/superset-api-dashboard.sh
Labels: waiting on author, open-source-contribution
