Repository openedx/tutor-contrib-aspects, pull requests merged in 2023-08, with the labels that each got.

#136 feat: support for asset translation
  .github/workflows/test-tutor-aspects.yml
  tutoraspects/patches/superset-extra-asset-translations
  tutoraspects/plugin.py
  tutoraspects/templates/aspects/apps/superset/pythonpath/create_assets.py
  tutoraspects/templates/aspects/apps/superset/pythonpath/locale.yaml
  tutoraspects/templates/aspects/apps/superset/pythonpath/openedx_sso_security_manager.py
  tutoraspects/templates/aspects/apps/superset/pythonpath/superset_config.py
  tutoraspects/templates/aspects/apps/superset/pythonpath/superset_config_docker.py
  tutoraspects/templates/aspects/apps/superset/security/roles.json
  tutoraspects/templates/base-docker-compose-services
  tutoraspects/templates/openedx-assets/Instructor_dashboard_9.yaml
  tutoraspects/templates/openedx-assets/Open_edX_Admin_Dashboard_2.yaml
  tutoraspects/templates/openedx-assets/Operator_Dashboard_5.yaml
Labels: waiting on author, open-source-contribution, core contributor, waiting for eng review

#263 chore: delete remote branch before release
  .github/workflows/bump-version.yaml
Labels: open-source-contribution

#266 fix: upgrade event-routing-backends to 5.5.4
  tutoraspects/plugin.py
Labels: open-source-contribution

#268 chore: correct bump version workflow
  .github/workflows/bump-version.yaml
  .github/workflows/compile-translations.yaml
Labels: open-source-contribution

#276 fix: use yaml delimiter to separate translations
  tutoraspects/templates/aspects/apps/superset/pythonpath/create_assets.py
  tutoraspects/templates/aspects/apps/superset/pythonpath/locale.yaml
Labels: open-source-contribution

#278 fix: remove loading locale file before processing
  tutoraspects/templates/aspects/apps/superset/pythonpath/create_assets.py
Labels: open-source-contribution

#281 feat: add superset owners configurable variable
  scripts/utils.py
  tutoraspects/plugin.py
  tutoraspects/templates/aspects/apps/superset/pythonpath/assets.yaml
  tutoraspects/templates/aspects/apps/superset/pythonpath/create_assets.py
  tutoraspects/templates/aspects/apps/superset/pythonpath/locale.yaml
  tutoraspects/templates/openedx-assets/Open_edX_Admin_Dashboard_2.yaml
  tutoraspects/templates/openedx-assets/assets/charts/Actor_IDs_over_time_47.yaml
  tutoraspects/templates/openedx-assets/assets/charts/Attempts_to_first_success_42.yaml
  tutoraspects/templates/openedx-assets/assets/charts/Courses_44.yaml
  tutoraspects/templates/openedx-assets/assets/charts/Cumulative_enrollments_by_mode_15.yaml
  tutoraspects/templates/openedx-assets/assets/charts/Enrolled_learners_per_day_36.yaml
  tutoraspects/templates/openedx-assets/assets/charts/Enrollment_events_per_day_16.yaml
  tutoraspects/templates/openedx-assets/assets/charts/Event_type_45.yaml
  tutoraspects/templates/openedx-assets/assets/charts/Events_per_course_46.yaml
  tutoraspects/templates/openedx-assets/assets/charts/Hints_and_answers_displayed_per_correct_answer_43.yaml
  tutoraspects/templates/openedx-assets/assets/charts/Last_course_syncronized_41.yaml
  tutoraspects/templates/openedx-assets/assets/charts/Last_received_xAPI_events_40.yaml
  tutoraspects/templates/openedx-assets/assets/charts/Organizations_42.yaml
  tutoraspects/templates/openedx-assets/assets/charts/Problem_submission_counts_38.yaml
  tutoraspects/templates/openedx-assets/assets/charts/Response_distribution_39.yaml
  tutoraspects/templates/openedx-assets/assets/charts/Synchronized_Courses_39.yaml
  tutoraspects/templates/openedx-assets/assets/charts/Transcript_closed_captioning_usage_per_video_11.yaml
  tutoraspects/templates/openedx-assets/assets/charts/Unique_actors_43.yaml
  tutoraspects/templates/openedx-assets/assets/charts/Watched_video_segments_51.yaml
  tutoraspects/templates/openedx-assets/assets/charts/Watches_per_video_10.yaml
  tutoraspects/templates/openedx-assets/assets/charts/xAPI_events_38.yaml
  tutoraspects/templates/openedx-assets/assets/dashboards/Instructor_dashboard_9.yaml
  tutoraspects/templates/openedx-assets/assets/dashboards/Operator_Dashboard_5.yaml
  tutoraspects/templates/openedx-assets/assets/databases/OpenedX_Clickhouse.yaml
  tutoraspects/templates/openedx-assets/assets/datasets/course_blocks.yaml
  tutoraspects/templates/openedx-assets/assets/datasets/course_overviews.yaml
  tutoraspects/templates/openedx-assets/assets/datasets/dim_course_problems.yaml
  tutoraspects/templates/openedx-assets/assets/datasets/dim_course_videos.yaml
  tutoraspects/templates/openedx-assets/assets/datasets/dim_courses.yaml
  tutoraspects/templates/openedx-assets/assets/datasets/fact_enrollments.yaml
  tutoraspects/templates/openedx-assets/assets/datasets/fact_enrollments_by_day.yaml
  tutoraspects/templates/openedx-assets/assets/datasets/fact_learner_problem_summary.yaml
  tutoraspects/templates/openedx-assets/assets/datasets/fact_problem_responses.yaml
  tutoraspects/templates/openedx-assets/assets/datasets/fact_transcript_usage.yaml
  tutoraspects/templates/openedx-assets/assets/datasets/fact_video_plays.yaml
  tutoraspects/templates/openedx-assets/assets/datasets/fact_watched_video_segments.yaml
  tutoraspects/templates/openedx-assets/assets/datasets/hints_per_success.yaml
  tutoraspects/templates/openedx-assets/assets/datasets/xapi_events_all_parsed.yaml
  tutoraspects/templates/openedx-assets/xAPI_events_by_course_11.yaml
  tutoraspects/templates/openedx-assets/xAPI_problem_events_by_block_7.yaml
Labels: open-source-contribution

#272 feat: use dbt models for problem datasets
  tutoraspects/plugin.py
  tutoraspects/templates/openedx-assets/assets/datasets/fact_learner_problem_summary.yaml
  tutoraspects/templates/openedx-assets/assets/datasets/fact_problem_responses.yaml
  tutoraspects/templates/openedx-assets/queries/fact_learner_problem_summary.sql
  tutoraspects/templates/openedx-assets/queries/fact_problem_responses.sql
  tutoraspects/templates/openedx-assets/queries/hints_per_success.sql
Labels: open-source-contribution

#288 fix: add configurable clickhouse volume size
  tutoraspects/patches/k8s-volumes
  tutoraspects/plugin.py
Labels: open-source-contribution

#291 fix: Adapted transform_tracking_logs command for enhanced CLI integration
  tutoraspects/commands_v0.py
  tutoraspects/commands_v1.py
Labels: open-source-contribution

#303 test: load images built in kind
  .github/workflows/test-tutor-aspects.yml
Labels: open-source-contribution

#305 feat: create component-specific tabs (FC-0033)
  tutoraspects/templates/openedx-assets/assets/dashboards/Instructor_dashboard.yaml
Labels: open-source-contribution

#309 refactor: use `course_run` instead of `run_name` (FC-0033)
  tutoraspects/plugin.py
  tutoraspects/templates/openedx-assets/assets/dashboards/Instructor_dashboard.yaml
  tutoraspects/templates/openedx-assets/assets/datasets/course_names.yaml
  tutoraspects/templates/openedx-assets/assets/datasets/dim_course_problems.yaml
  tutoraspects/templates/openedx-assets/assets/datasets/dim_course_videos.yaml
  tutoraspects/templates/openedx-assets/assets/datasets/fact_enrollments.yaml
  tutoraspects/templates/openedx-assets/assets/datasets/fact_enrollments_by_day.yaml
  tutoraspects/templates/openedx-assets/assets/datasets/fact_learner_problem_summary.yaml
  tutoraspects/templates/openedx-assets/assets/datasets/fact_problem_responses.yaml
  tutoraspects/templates/openedx-assets/assets/datasets/fact_transcript_usage.yaml
  tutoraspects/templates/openedx-assets/assets/datasets/fact_video_plays.yaml
  tutoraspects/templates/openedx-assets/assets/datasets/fact_watched_video_segments.yaml
  tutoraspects/templates/openedx-assets/assets/datasets/hints_per_success.yaml
  tutoraspects/templates/openedx-assets/queries/dim_course_problems.sql
  tutoraspects/templates/openedx-assets/queries/dim_course_videos.sql
  tutoraspects/templates/openedx-assets/queries/dim_courses.sql
  tutoraspects/templates/openedx-assets/queries/fact_enrollments_by_day.sql
  tutoraspects/templates/openedx-assets/queries/fact_watched_video_segments.sql
  tutoraspects/templates/openedx-assets/queries/hints_per_success.sql
Labels: open-source-contribution

#316 fix: filter out unsuccessful responses in "attempts to first success" chart (FC-0033)
  tutoraspects/templates/openedx-assets/assets/charts/Attempts_to_first_success.yaml
Labels: open-source-contribution

#314 refactor: use course_key index in dashboard queries (FC-0033)
  tutoraspects/templates/openedx-assets/assets/datasets/fact_enrollments.yaml
  tutoraspects/templates/openedx-assets/assets/datasets/fact_enrollments_by_day.yaml
  tutoraspects/templates/openedx-assets/assets/datasets/fact_learner_problem_summary.yaml
  tutoraspects/templates/openedx-assets/assets/datasets/fact_problem_responses.yaml
  tutoraspects/templates/openedx-assets/assets/datasets/fact_transcript_usage.yaml
  tutoraspects/templates/openedx-assets/assets/datasets/fact_video_plays.yaml
  tutoraspects/templates/openedx-assets/assets/datasets/fact_watched_video_segments.yaml
  tutoraspects/templates/openedx-assets/assets/datasets/hints_per_success.yaml
  tutoraspects/templates/openedx-assets/queries/common_filters.sql
  tutoraspects/templates/openedx-assets/queries/fact_enrollments.sql
  tutoraspects/templates/openedx-assets/queries/fact_enrollments_by_day.sql
  tutoraspects/templates/openedx-assets/queries/fact_learner_problem_summary.sql
  tutoraspects/templates/openedx-assets/queries/fact_problem_responses.sql
  tutoraspects/templates/openedx-assets/queries/fact_transcript_usage.sql
  tutoraspects/templates/openedx-assets/queries/fact_video_plays.sql
  tutoraspects/templates/openedx-assets/queries/fact_watched_video_segments.sql
  tutoraspects/templates/openedx-assets/queries/hints_per_success.sql
Labels: open-source-contribution

#307 feat: Add student role with minimal access in Superset
  tutoraspects/plugin.py
  tutoraspects/templates/aspects/apps/superset/pythonpath/openedx_sso_security_manager.py
  tutoraspects/templates/aspects/apps/superset/pythonpath/superset_config_docker.py
  tutoraspects/templates/aspects/apps/superset/security/partials/read_only_permissions.json
  tutoraspects/templates/aspects/apps/superset/security/roles.json
Labels: waiting on author, open-source-contribution

#319 feat: add RLS filters for dbt models (FC-0033)
  tutoraspects/patches/superset-row-level-security
Labels: open-source-contribution

#299 fix: add cache wrapper for can_view_courses filter
  tutoraspects/templates/aspects/apps/superset/pythonpath/openedx_sso_security_manager.py
  tutoraspects/templates/aspects/apps/superset/pythonpath/superset_config_docker.py
Labels: waiting on author, open-source-contribution, core contributor

#326 fix: print packages and project dbt correctly
  tutoraspects/templates/aspects/apps/aspects/scripts/dbt.sh
Labels: open-source-contribution

#323 fix: add option to deduplicate tables after backfill
  README.rst
  tutoraspects/commands_v0.py
  tutoraspects/commands_v1.py
  tutoraspects/templates/aspects/jobs/init/clickhouse/deduplicate.sh
Labels: open-source-contribution

#328 fix: print packages and project dbt correctly
  tutoraspects/templates/aspects/jobs/init/aspects/init-aspects.sh
Labels: open-source-contribution

#332 feat: upgrade event-routing-backends to 5.6.0
  tutoraspects/plugin.py
Labels: open-source-contribution

#325 feat: include language code in translated asset name (FC-0033)
  tutoraspects/templates/aspects/apps/superset/pythonpath/create_assets.py
Labels: open-source-contribution

#336 feat: upgrade dbt-aspects to v2.2
  tutoraspects/plugin.py
Labels: open-source-contribution

#339 chore: bump xapi-db-load and aspects-dbt versions (FC-0033)
  tutoraspects/plugin.py
  tutoraspects/templates/aspects/build/aspects/requirements.txt
Labels: open-source-contribution
